version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - bff
    networks:
      - grpc-test-network
    restart: unless-stopped

  bff:
    build:
      context: ./bff
    ports:
      - "8000:8000"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - backend
    networks:
      - grpc-test-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    volumes:
      - ./proto:/app/proto
    depends_on:
      - db
    networks:
      - grpc-test-network
    restart: unless-stopped

  db:
    build:
      context: ./db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - grpc-test-network
    restart: unless-stopped

networks:
  grpc-test-network:
    driver: bridge

volumes:
  postgres-data: