# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0buserservice\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"<\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"3\n\x10ListUsersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"R\n\x11ListUsersResponse\x12(\n\x05users\x18\x01 \x03(\x0b\x32\x19.userservice.UserResponse\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2\xe8\x01\n\x0bUserService\x12@\n\x07GetUser\x12\x18.userservice.UserRequest\x1a\x19.userservice.UserResponse\"\x00\x12L\n\tListUsers\x12\x1d.userservice.ListUsersRequest\x1a\x1e.userservice.ListUsersResponse\"\x00\x12I\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x19.userservice.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=30
  _globals['_USERREQUEST']._serialized_end=60
  _globals['_USERRESPONSE']._serialized_start=62
  _globals['_USERRESPONSE']._serialized_end=122
  _globals['_LISTUSERSREQUEST']._serialized_start=124
  _globals['_LISTUSERSREQUEST']._serialized_end=175
  _globals['_LISTUSERSRESPONSE']._serialized_start=177
  _globals['_LISTUSERSRESPONSE']._serialized_end=259
  _globals['_CREATEUSERREQUEST']._serialized_start=261
  _globals['_CREATEUSERREQUEST']._serialized_end=309
  _globals['_USERSERVICE']._serialized_start=312
  _globals['_USERSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
