apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: grpc-error-handling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-service
        image: grpc-error-handling-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: BFF_SERVICE_ADDRESS
          value: "bff-service:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: grpc-error-handling
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer